apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-enterprise-mkdirs
  annotations:
    {{- if .Values.argocd }}
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/hook: "Sync"
    {{- else }}
    helm.sh/hook: "pre-install,pre-upgrade"
    helm.sh/hook-weight: "-1"
    {{- end }}
spec:
  parallelism: 1
  completions: 1
  template:
    spec:
      serviceAccountName: {{ .Release.Namespace }}-main
      restartPolicy: Never
      {{- if .Values.fbconfig.hostAliases }}
      hostAliases:
        {{- toYaml .Values.fbconfig.hostAliases | nindent 8 }}
      {{- end }}
      containers:
        - name: enterprise-mkdirs
          image: {{ .Values.image.registry }}alpine:3.17.5
          command: ["/bin/sh", "-c"]
          args:
            - >
                install -o 1000 -g 1000 -d /opt/feedback/ivr;
                install -o 1000 -g 1000 -d /opt/feedback/export;
                install -o 1000 -g 1000 -d /opt/feedback/export/archive;
                install -o 1000 -g 1000 -d /opt/feedback/import;
                install -o 1000 -g 1000 -d /opt/feedback/import/archive;
              {{- range $enterprise := .Values.enterprises }}
                install -o 1000 -g 1000 -d /opt/feedback/export/{{ $enterprise.name }};
                install -o 1000 -g 1000 -d /opt/feedback/import/{{ $enterprise.name }};
                install -o 1000 -g 1000 -d /opt/feedback/import/{{ $enterprise.name }}/.locks;
                install -o 1000 -g 1000 -d /opt/feedback/ivr/{{ $enterprise.name }};
                install -o 1000 -g 1000 -d /opt/feedback/staticfiles/{{ $enterprise.name }};
              {{- end }}
          volumeMounts:
            - name: export-data
              mountPath: /opt/feedback
              readOnly: false
            {{- if .Values.ivr.enabled }}
            - name: ivr-data
              mountPath: /opt/feedback/ivr
              readOnly: false
            {{- end }}
      volumes:
        - name: export-data
          persistentVolumeClaim:
            claimName: {{ .Values.fbconfig.claim }}
        {{- if .Values.ivr.enabled }}
        - name: ivr-data
          persistentVolumeClaim:
            claimName: ivr
        {{- end }}
