apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: privileged-psp-role
  namespace: default
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs: ['use']
  resourceNames:
  - pks-privileged

