apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: use-pks-privileged-psp
rules:
- apiGroups:
  - policy
  resourceNames:
  - pks-privileged
  resources:
  - podsecuritypolicies
  verbs:
  - use

