apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentd-cluster-role
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces", "pods/log"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluentd-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: default-main  # Make sure this matches the service account used by Fluentd
  namespace: default  # And this matches the namespace where Fluentd is running
roleRef:
  kind: ClusterRole
  name: fluentd-cluster-role
  apiGroup: rbac.authorization.k8s.io

