apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-02-21T23:15:00Z"
  labels:
    run: netshoot
  name: netshoot
  namespace: default
  resourceVersion: "157221686"
  uid: 5aa7eb17-422c-4c6b-80f2-0c56884eb9fc
spec:
  containers:
  - args:
    - /bin/bash
    image: nicolaka/netshoot
    imagePullPolicy: Always
    name: netshoot
    resources: {}
    stdin: true
    stdinOnce: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-l2j22
      readOnly: true
    - name: cacert-volume
      mountPath: /etc/ssl/certs/cacert.crt
      subPath: cacert.crt
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: gcr-json-key
  nodeName: eca554da-bea6-4d84-8289-9d6e2a539590
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-l2j22
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
  - name: cacert-volume
    configMap:
      name: cacert-configmap
      items:
      - key: cacert.crt
        path: cacert.crt
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-02-21T23:15:00Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-02-21T23:15:05Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-02-21T23:15:05Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-02-21T23:15:00Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://f2afc0ab65bb0338c8f1d2e09c570d9e99c427462edd3476e1787946c643096c
    image: docker.io/nicolaka/netshoot:latest
    imageID: docker.io/nicolaka/netshoot@sha256:b569665f0c32391b93f4de344f07bf6353ddff9d8c801ac3318d996db848a64c
    lastState: {}
    name: netshoot
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-02-21T23:15:04Z"
  hostIP: 10.155.4.6
  phase: Running
  podIP: 10.156.42.12
  podIPs:
  - ip: 10.156.42.12
  qosClass: BestEffort
  startTime: "2024-02-21T23:15:00Z"
