apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: permissive-psp
spec:
  privileged: true
  allowPrivilegeEscalation: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  readOnlyRootFilesystem: false
  volumes:
  - '*'

