apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-scrape
subjects:
- kind: ServiceAccount
  name: prometheus-server  # Change this to your Prometheus Service Account
  namespace: monitoring
roleRef:
  kind: ClusterRole
  name: prometheus-scrape
  apiGroup: rbac.authorization.k8s.io

