apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: default-main
  namespace: default
roleRef:
  kind: Role
  name: psp-role
  apiGroup: rbac.authorization.k8s.io

