apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-vault-1
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-vault-1

