apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-rabbitmq-0
  labels:
    type: local
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: vochub
  hostPath:
    path: "/mnt/data/rabbitmq-0"
    type: DirectoryOrCreate

