apiVersion: v1
kind: Pod
metadata:
  name: passwordsafe-integration
  namespace: default
spec:
  volumes:
    - name: secrets
      emptyDir:
        medium: Memory
    - name: certificate
      secret:
        secretName: common-tlssecret
  initContainers:
    - name: secrets-agent
      image: memoor/secrets-agent:latest
      imagePullPolicy: IfNotPresent  # Change this if necessary
      volumeMounts:
        - name: secrets
          mountPath: /usr/src/app/secrets_files
        - name: certificate
          mountPath: /usr/src/app/certificate
      ports:
        - containerPort: 8000
          name: secrets-agent
      resources:
        limits:
          memory: "400Mi"
      env:
      - name: SECRETS_PATH
        value: "/usr/src/app/secrets_files"
      - name: BT_API_URL
        value: "https://rwrmpam1c.mtn.co.rw:443/BeyondTrust/api/public/v3"
      - name: BT_API_KEY
        valueFrom:
          secretKeyRef:
            name: beyondtrust-api-key
            key: api-key
      - name: SECRETS_LIST
        value: "rootFolder/childFolder1/secretTitle"
      - name: FOLDER_LIST
        value: "rootFolder/childFolder2/"
      - name: MANAGED_ACCOUNTS_LIST
        value: "Server2016Standard/serveruser1"
      - name: BT_VERIFY_CA
        value: "True"
      - name: BT_CLIENT_CERTIFICATE_PATH
        value: "/usr/src/app/certificate/tls.crt"
      - name: BT_CLIENT_CERTIFICATE_PASSWORD
        value: "***************"
  containers:
    - name: my-app
      image: my-app-image:latest
      imagePullPolicy: IfNotPresent  # Change this if necessary
      volumeMounts:
        - name: secrets
          mountPath: /usr/src/app/secrets_files
      env:
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: db-secret
            key: db-password

