apiVersion: v1
kind: Pod
metadata:
  name: temp-cp-pod
  namespace: vault
spec:
  containers:
  - name: temp-cp-container
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - name: vault-plugins
      mountPath: /mnt/vault/plugins
  volumes:
  - name: vault-plugins
    persistentVolumeClaim:
      claimName: vault-plugins-pvc

