apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      serviceAccountName: default-main
      containers:
      - name: test-container
        image: nginx  # You can use any image for testing
        ports:
        - containerPort: 80

