apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yourls
{{- if or .Values.global.externalDNSHostTarget (.Values.global.ingressAnnotations | default .Values.yourls.ingressAnnotations) }}
  annotations:
  {{- if .Values.global.externalDNSHostTarget }}
    external-dns.alpha.kubernetes.io/target: {{ .Values.global.externalDNSHostTarget }}
  {{- end }}
  {{- range $k, $v := merge .Values.yourls.ingressAnnotations .Values.global.ingressAnnotations }}
    {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}

spec:
{{- if .Values.global.ingressClass }}
  ingressClassName: {{ .Values.global.ingressClass | quote }}
{{- end }}
  rules:
  {{- range .Values.yourls.app.hosts }}
    - host: {{ . }}
      http:
        paths:
        - path: /
          pathType: "Prefix"
          backend:
            service:
              name: yourls
              port:
                name: yrls-http-port
  {{- end }}
