apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-init-db
  annotations:
    {{- if .Values.argocd }}
    argocd.argoproj.io/sync-wave: "-2"
    argocd.argoproj.io/hook: "Sync"
    {{- else }}
    helm.sh/hook: "pre-install,pre-upgrade"
    helm.sh/hook-weight: "-2"
    {{- end }}

spec:
  parallelism: 1
  completions: 1
  template:
    spec:
      serviceAccountName: {{ .Release.Namespace }}-main
      restartPolicy: Never
    {{- if .Values.mysql.customCaCert }}
      initContainers:
        {{- include "yourls.customCaInitContainer" . | nindent 8 }}
    {{- end }}
      containers:
        - name: yourls-init-db
          image: {{ .Values.image.registry }}mysql:8.0
          command: ["/bin/sh", "-ec"]
          args:
            - >
              mysql {{ include "yourls.mysqlCliOptions" . }} -e "CREATE DATABASE IF NOT EXISTS ${YOURLS_DB_NAME} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;";
              mysql {{ include "yourls.mysqlCliOptions" . }} -e "ALTER DATABASE ${YOURLS_DB_NAME} CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;";
              mysql {{ include "yourls.mysqlCliOptions" . }} -e "USE ${YOURLS_DB_NAME}; SOURCE /yourls.sql;"
          env:
            - name: YOURLS_DB_HOST
              value: {{ .Values.yourls.db.host }}
            - name: YOURLS_DB_NAME
              value: {{ .Values.yourls.db.name }}
            - name: YOURLS_DB_USER
              value: {{ .Values.yourls.db.username }}
            - name: YOURLS_DB_PASS
              value: {{ .Values.yourls.db.password | quote }}

          volumeMounts:
            - name: yourls-sql
              mountPath: /yourls.sql
              subPath: yourls.sql
          {{- if .Values.mysql.customCaCert }}
            - name: ssl-certs
              mountPath: /etc/ssl/certs
              readOnly: false
          {{- end }}
      volumes:
        - name: yourls-sql
          configMap:
            name: yourls-sql
      {{- if .Values.mysql.customCaCert }}
        - name: mysql-custom-ca
          configMap:
            name: mysql-custom-ca
        - name: ssl-certs
          emptyDir: {}
      {{- end }}
