apiVersion: v1
kind: Service
metadata:
  name: feedback-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: fb-api-http-port
  selector:
    app: feedback-api
