apiVersion: v1
kind: Secret
metadata:
  name: keda-rabbitmq-secret
data:
  host: {{ .Values.rabbitmqHost | b64enc | quote }}
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-rabbitmq-trigger
spec:
  secretTargetRef:
  - parameter: host
    name: keda-rabbitmq-secret
    key: host
