apiVersion: batch/v1
kind: CronJob
metadata:
  name: sso-clean-old-sessions
spec:
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 10
  concurrencyPolicy: Forbid
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            grp: sso
        spec:
          serviceAccountName: {{ .Release.Namespace }}-main
          automountServiceAccountToken: false
          restartPolicy: Never
        {{- if .Values.mysql.customCaCert }}
          initContainers:
            {{- include "sso.customCaInitContainer" . | nindent 12 }}
        {{- end }}
          containers:
            - name: sso-clean-old-sessions
              image: {{ .Values.image.repository }}/sso:{{ .Values.sso.image.tag }}
              command: ["sso-mgm"]
              args: ["clean_old_sessions"]
              volumeMounts:
                - name: sso-config
                  mountPath: /etc/sso/
                - name: sso-adfs
                  mountPath: /etc/sso/adfs/
              {{- if .Values.mysql.customCaCert }}
                - name: ssl-certs
                  mountPath: /etc/ssl/certs
                  readOnly: false
              {{- end }}
              env:
                - name: TZ
                  value: {{ .Values.global.timeZone }}
                - name: SSO_DB_HOST
                  value: {{ .Values.sso.db.host | quote }}
                - name: SSO_DB_PORT
                  value: {{ .Values.sso.db.port | quote }}
                - name: SSO_DB_NAME
                  value: {{ .Values.sso.db.name | quote }}
                - name: SSO_DB_USER
                  value: {{ .Values.sso.db.username | quote }}
                - name: SSO_DB_PASSWORD
                  value: {{ .Values.sso.db.password | quote }}
              {{- if .Values.mysql.tls }}
                - name: DB_SSL_MODE
                  value: VERIFY_IDENTITY
                - name: DB_SSL_CA
                  value: /etc/ssl/certs/ca-certificates.crt
              {{- end }}
          volumes:
            - name: sso-config
              configMap:
                name: sso-config
            - name: sso-adfs
              configMap:
                name: sso-adfs
          {{- if .Values.mysql.customCaCert }}
            - name: mysql-custom-ca
              configMap:
                name: mysql-custom-ca
            - name: ssl-certs
              emptyDir: {}
          {{- end }}
