apiVersion: v1
kind: Service
metadata:
  name: sso
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: sso-http-port
  - port: 443
    targetPort: 8443
    protocol: TCP
    name: sso-ssl-http-port
  selector:
    app: sso
