apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-json
  {{- if .Values.argocd }}
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  {{- end }}
type: Opaque
stringData:
  load_definition.json: |-
    {
      "users": {{ toJson .Values.users }},
      "vhosts": [
        {"name": "/"}
      ],
      "permissions": {{ toJson .Values.permissions }},
      "policies": [
        {"name": "HA", "pattern": ".*", "vhost": "/", "definition": {"ha-mode": "exactly", "ha-params": 2, "ha-sync-mode": "automatic"}}
      ]
    }
