apiVersion: v1
kind: Service
metadata:
  name: notification-manager
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: {{ .Values.nm.ingress.port }}
    protocol: TCP
    name: nm-http
  selector:
    app: notification-manager
