k9s:
  cluster: VOC_CLUSTER
  namespace:
    active: all
    lockFavorites: false
    favorites:
    - all
  view:
    active: pod
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
