apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "11"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"10","meta.helm.sh/release-name":"keda","meta.helm.sh/release-namespace":"default"},"creationTimestamp":"2024-02-04T00:25:26Z","generation":10,"labels":{"app":"keda-operator-metrics-apiserver","app.kubernetes.io/component":"operator","app.kubernetes.io/instance":"keda","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"keda-operator-metrics-apiserver","app.kubernetes.io/part-of":"keda-operator","app.kubernetes.io/version":"2.10.1","helm.sh/chart":"keda-2.10.2"},"name":"keda-operator-metrics-apiserver","namespace":"default","resourceVersion":"151589082","uid":"da800414-0a5e-4bd7-84b1-8fed7f45f68f"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"keda-operator-metrics-apiserver"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"keda-operator-metrics-apiserver","app.kubernetes.io/component":"operator","app.kubernetes.io/instance":"keda","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"keda-operator-metrics-apiserver","app.kubernetes.io/part-of":"keda-operator","app.kubernetes.io/version":"2.10.1","helm.sh/chart":"keda-2.10.2"}},"spec":{"automountServiceAccountToken":true,"containers":[{"args":["/usr/local/bin/keda-adapter","--port=8080","--secure-port=6443","--logtostderr=true","--metrics-service-address=keda-operator.default.svc.cluster.local:9666","--client-ca-file=/certs/ca.crt","--tls-cert-file=/certs/tls.crt","--tls-private-key-file=/certs/tls.key","--cert-dir=/certs","--v=0"],"env":[{"name":"WATCH_NAMESPACE"},{"name":"POD_NAMESPACE","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.namespace"}}},{"name":"KEDA_HTTP_DEFAULT_TIMEOUT","value":"3000"},{"name":"KEDA_HTTP_MIN_TLS_VERSION","value":"TLS12"}],"image":"europe-docker.pkg.dev/sandsiv-infrastructure/vochub/keda-metrics-apiserver:v2.10-ss","imagePullPolicy":"IfNotPresent","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/healthz","port":6443,"scheme":"HTTPS"},"initialDelaySeconds":5,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":1},"name":"keda-operator-metrics-apiserver","ports":[{"containerPort":6443,"name":"https","protocol":"TCP"},{"containerPort":8080,"name":"http","protocol":"TCP"}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/readyz","port":6443,"scheme":"HTTPS"},"initialDelaySeconds":5,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":1},"resources":{"limits":{"cpu":"1","memory":"500Mi"},"requests":{"cpu":"100m","memory":"100Mi"}},"securityContext":{"allowPrivilegeEscalation":false,"capabilities":{"drop":["ALL"]},"readOnlyRootFilesystem":true,"seccompProfile":{"type":"RuntimeDefault"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/certs","name":"certificates","readOnly":true},{"mountPath":"/etc/ssl/certs/custom","name":"custom-ca-certificates","readOnly":true}]}],"dnsPolicy":"ClusterFirst","nodeSelector":{"kubernetes.io/os":"linux"},"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{"runAsNonRoot":true},"serviceAccount":"keda-operator","serviceAccountName":"keda-operator","terminationGracePeriodSeconds":30,"volumes":[{"name":"certificates","secret":{"defaultMode":420,"secretName":"kedaorg-certs"}},{"configMap":{"name":"custom-ca-certificates"},"name":"custom-ca-certificates"}]}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2024-02-04T00:25:37Z","lastUpdateTime":"2024-02-04T00:25:37Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2024-02-04T00:25:26Z","lastUpdateTime":"2024-02-05T04:39:07Z","message":"ReplicaSet \"keda-operator-metrics-apiserver-577b8bd6c6\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":10,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
    meta.helm.sh/release-name: keda
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2024-02-04T00:25:26Z"
  generation: 11
  labels:
    app: keda-operator-metrics-apiserver
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: keda
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keda-operator-metrics-apiserver
    app.kubernetes.io/part-of: keda-operator
    app.kubernetes.io/version: 2.10.1
    helm.sh/chart: keda-2.10.2
  name: keda-operator-metrics-apiserver
  namespace: default
  resourceVersion: "151598218"
  uid: da800414-0a5e-4bd7-84b1-8fed7f45f68f
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: keda-operator-metrics-apiserver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: keda-operator-metrics-apiserver
        app.kubernetes.io/component: operator
        app.kubernetes.io/instance: keda
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: keda-operator-metrics-apiserver
        app.kubernetes.io/part-of: keda-operator
        app.kubernetes.io/version: 2.10.1
        helm.sh/chart: keda-2.10.2
    spec:
      automountServiceAccountToken: true
      containers:
      - args:
        - /usr/local/bin/keda-adapter
        - --port=8080
        - --secure-port=6443
        - --logtostderr=true
        - --metrics-service-address=keda-operator.default.svc.cluster.local:9666
        - --client-ca-file=/certs/ca.crt
        - --tls-cert-file=/certs/tls.crt
        - --tls-private-key-file=/certs/tls.key
        - --cert-dir=/certs
        - --v=0
        env:
        - name: WATCH_NAMESPACE
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: KEDA_HTTP_DEFAULT_TIMEOUT
          value: "3000"
        - name: KEDA_HTTP_MIN_TLS_VERSION
          value: TLS12
        image: europe-docker.pkg.dev/sandsiv-infrastructure/vochub/keda-metrics-apiserver:v2.10-ss
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 6443
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: keda-operator-metrics-apiserver
        ports:
        - containerPort: 6443
          name: https
          protocol: TCP
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: 6443
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          seccompProfile:
            type: RuntimeDefault
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /certs
          name: certificates
          readOnly: true
        - mountPath: /etc/ssl/certs/custom
          name: custom-ca-certificates
          readOnly: true
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
      serviceAccount: keda-operator
      serviceAccountName: keda-operator
      terminationGracePeriodSeconds: 30
      volumes:
      - name: certificates
        secret:
          defaultMode: 420
          secretName: kedaorg-certs
      - configMap:
          defaultMode: 420
          name: custom-ca-certificates
        name: custom-ca-certificates
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-02-04T00:25:37Z"
    lastUpdateTime: "2024-02-04T00:25:37Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-02-04T00:25:26Z"
    lastUpdateTime: "2024-02-05T05:10:38Z"
    message: ReplicaSet "keda-operator-metrics-apiserver-6fd95488b8" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 11
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
