apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "10"
    meta.helm.sh/release-name: keda
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2024-02-04T00:25:26Z"
  generation: 10
  labels:
    app: keda-operator
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: keda
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keda-operator
    app.kubernetes.io/part-of: keda-operator
    app.kubernetes.io/version: 2.10.1
    helm.sh/chart: keda-2.10.2
    name: keda-operator
  name: keda-operator
  namespace: default
  resourceVersion: "151589279"
  uid: 9188cebc-5552-4cdf-a6cd-68fa098a8685
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: keda-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: keda-operator
        app.kubernetes.io/component: operator
        app.kubernetes.io/instance: keda
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: keda-operator
        app.kubernetes.io/part-of: keda-operator
        app.kubernetes.io/version: 2.10.1
        helm.sh/chart: keda-2.10.2
        name: keda-operator
    spec:
      automountServiceAccountToken: true
      containers:
      - args:
        - --leader-elect
        - --zap-log-level=info
        - --zap-encoder=console
        - --zap-time-encoding=rfc3339
        - --cert-dir=/certs
        - --enable-cert-rotation=true
        - --cert-secret-name=kedaorg-certs
        - --operator-service-name=keda-operator
        - --metrics-server-service-name=keda-operator-metrics-apiserver
        - --webhooks-service-name=keda-admission-webhooks
        command:
        - /keda
        env:
        - name: WATCH_NAMESPACE
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: OPERATOR_NAME
          value: keda-operator
        - name: KEDA_HTTP_DEFAULT_TIMEOUT
          value: "3000"
        - name: KEDA_HTTP_MIN_TLS_VERSION
          value: TLS12
        image: europe-docker.pkg.dev/sandsiv-infrastructure/vochub/keda:v2.10-ss
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 25
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: keda-operator
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          seccompProfile:
            type: RuntimeDefault
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /certs
          name: certificates
          readOnly: true
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
      serviceAccount: keda-operator
      serviceAccountName: keda-operator
      terminationGracePeriodSeconds: 30
      volumes:
      - name: certificates
        secret:
          defaultMode: 420
          optional: true
          secretName: kedaorg-certs
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-02-04T17:36:04Z"
    lastUpdateTime: "2024-02-04T17:36:04Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-02-04T00:25:26Z"
    lastUpdateTime: "2024-02-05T04:39:26Z"
    message: ReplicaSet "keda-operator-5cdd7f7444" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 10
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
