apiVersion: v1
entries:
  k8sgpt-operator:
  - annotations:
      artifacthub.io/categories: monitoring-logging
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: support
          url: https://github.com/k8sgpt-ai/k8sgpt-operator/issues/new
        - name: community
          url: https://github.com/k8sgpt-ai/community
    apiVersion: v2
    appVersion: 0.0.26
    created: "2024-02-02T08:13:57.324464749Z"
    description: Automatic SRE Superpowers within your Kubernetes cluster
    digest: c1707c856892ccccdc05f09ca7ad22f9e69b89d17dd360b420941d2f035c06a1
    maintainers:
    - email: noreply@k8sgpt.ai
      name: The K8sGPT Authors
      url: https://github.com/k8sgpt-ai/community
    name: k8sgpt-operator
    type: application
    urls:
    - https://charts.k8sgpt.ai/k8sgpt-operator-0.1.0.tgz
    version: 0.1.0
  - annotations:
      artifacthub.io/categories: monitoring-logging
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: support
          url: https://github.com/k8sgpt-ai/k8sgpt-operator/issues/new
        - name: community
          url: https://github.com/k8sgpt-ai/community
    apiVersion: v2
    appVersion: 0.0.26
    created: "2024-01-14T20:15:53.21159745Z"
    description: Automatic SRE Superpowers within your Kubernetes cluster
    digest: b15653c4288ad54c0f4bf69b1014cb94ebbdc1f0352e0011ad2b63d949547aa8
    maintainers:
    - email: noreply@k8sgpt.ai
      name: The K8sGPT Authors
      url: https://github.com/k8sgpt-ai/community
    name: k8sgpt-operator
    type: application
    urls:
    - https://charts.k8sgpt.ai/k8sgpt-operator-0.0.28.tgz
    version: 0.0.28
  - annotations:
      artifacthub.io/categories: monitoring-logging
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: support
          url: https://github.com/k8sgpt-ai/k8sgpt-operator/issues/new
        - name: community
          url: https://github.com/k8sgpt-ai/community
    apiVersion: v2
    appVersion: 0.0.26
    created: "2023-12-14T15:01:37.187998493Z"
    description: Automatic SRE Superpowers within your Kubernetes cluster
    digest: 5f13998e24e83cfb3ea81a9222a2f90960626fa7ecfd13810be95fdc92f8975e
    maintainers:
    - email: noreply@k8sgpt.ai
      name: The K8sGPT Authors
      url: https://github.com/k8sgpt-ai/community
    name: k8sgpt-operator
    type: application
    urls:
    - https://charts.k8sgpt.ai/k8sgpt-operator-0.0.27.tgz
    version: 0.0.27
  - annotations:
      artifacthub.io/categories: monitoring-logging
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: support
          url: https://github.com/k8sgpt-ai/k8sgpt-operator/issues/new
        - name: community
          url: https://github.com/k8sgpt-ai/community
    apiVersion: v2
    appVersion: 0.0.26
    created: "2023-12-02T19:37:07.28364373Z"
    description: Automatic SRE Superpowers within your Kubernetes cluster
    digest: 153055f556f9678188b892ed7aacdabf3e5a148d99a62e56f96561d832c28c6b
    maintainers:
    - email: noreply@k8sgpt.ai
      name: The K8sGPT Authors
      url: https://github.com/k8sgpt-ai/community
    name: k8sgpt-operator
    type: application
    urls:
    - https://charts.k8sgpt.ai/k8sgpt-operator-0.0.26.tgz
    version: 0.0.26
  - annotations:
      artifacthub.io/categories: monitoring-logging
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: support
          url: https://github.com/k8sgpt-ai/k8sgpt-operator/issues/new
        - name: community
          url: https://github.com/k8sgpt-ai/community
    apiVersion: v2
    appVersion: 0.0.25
    created: "2023-12-01T10:23:51.710485271Z"
    description: Automatic SRE Superpowers within your Kubernetes cluster
    digest: ebd4b3e04c67c519c33da82e156ff54ef2d3f6bfcf7e0e4c2f57bf275ac9626a
    maintainers:
    - email: noreply@k8sgpt.ai
      name: The K8sGPT Authors
      url: https://github.com/k8sgpt-ai/community
    name: k8sgpt-operator
    type: application
    urls:
    - https://charts.k8sgpt.ai/k8sgpt-operator-0.0.25.tgz
    version: 0.0.25
  - annotations:
      artifacthub.io/categories: monitoring-logging
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: support
          url: https://github.com/k8sgpt-ai/k8sgpt-operator/issues/new
        - name: community
          url: https://github.com/k8sgpt-ai/community
    apiVersion: v2
    appVersion: 0.0.24
    created: "2023-11-16T16:05:50.405830397Z"
    description: Automatic SRE Superpowers within your Kubernetes cluster
    digest: 22bf39b24c4f51337ad25a21d1a4ada886183db75298290cc838cc3680e63b89
    maintainers:
    - email: noreply@k8sgpt.ai
      name: The K8sGPT Authors
      url: https://github.com/k8sgpt-ai/community
    name: k8sgpt-operator
    type: application
    urls:
    - https://charts.k8sgpt.ai/k8sgpt-operator-0.0.24.tgz
    version: 0.0.24
  - annotations:
      artifacthub.io/categories: monitoring-logging
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: support
          url: https://github.com/k8sgpt-ai/k8sgpt-operator/issues/new
        - name: community
          url: https://github.com/k8sgpt-ai/community
    apiVersion: v2
    appVersion: 0.0.23
    created: "2023-11-12T12:44:03.969006378Z"
    description: Automatic SRE Superpowers within your Kubernetes cluster
    digest: 794695c7c0c9f5726b866848cf2446721f24942e67fb50724fb82b790c765d65
    maintainers:
    - email: noreply@k8sgpt.ai
      name: The K8sGPT Authors
      url: https://github.com/k8sgpt-ai/community
    name: k8sgpt-operator
    type: application
    urls:
    - https://charts.k8sgpt.ai/k8sgpt-operator-0.0.23.tgz
    version: 0.0.23
  - annotations:
      artifacthub.io/categories: monitoring-logging
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: support
          url: https://github.com/k8sgpt-ai/k8sgpt-operator/issues/new
        - name: community
          url: https://github.com/k8sgpt-ai/community
    apiVersion: v2
    appVersion: 0.0.22
    created: "2023-10-15T19:33:56.925245453Z"
    description: Automatic SRE Superpowers within your Kubernetes cluster
    digest: e21e2857a3a0bd66c97449e72223b419d328b137fbf67de9727562742984ba3a
    maintainers:
    - email: noreply@k8sgpt.ai
      name: The K8sGPT Authors
      url: https://github.com/k8sgpt-ai/community
    name: k8sgpt-operator
    type: application
    urls:
    - https://charts.k8sgpt.ai/k8sgpt-operator-0.0.22.tgz
    version: 0.0.22
  - annotations:
      artifacthub.io/categories: monitoring-logging
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: support
          url: https://github.com/k8sgpt-ai/k8sgpt-operator/issues/new
        - name: community
          url: https://github.com/k8sgpt-ai/community
    apiVersion: v2
    appVersion: 0.0.21
    created: "2023-08-28T12:56:40.209027798Z"
    description: Automatic SRE Superpowers within your Kubernetes cluster
    digest: b51c267891298997702066d8892dbc7ae62a3935c42e837ca4d0a1850a938f4c
    maintainers:
    - email: noreply@k8sgpt.ai
      name: The K8sGPT Authors
      url: https://github.com/k8sgpt-ai/community
    name: k8sgpt-operator
    type: application
    urls:
    - https://charts.k8sgpt.ai/k8sgpt-operator-0.0.21.tgz
    version: 0.0.21
  - annotations:
      artifacthub.io/categories: monitoring-logging
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: support
          url: https://github.com/k8sgpt-ai/k8sgpt-operator/issues/new
        - name: community
          url: https://github.com/k8sgpt-ai/community
    apiVersion: v2
    appVersion: 0.0.20
    created: "2023-08-01T18:02:26.118984729Z"
    description: Automatic SRE Superpowers within your Kubernetes cluster
    digest: 97c8589ee1b32e84bfce98d27aa84c7e33554ef81357df58d65fe194f63afc4a
    maintainers:
    - email: noreply@k8sgpt.ai
      name: The K8sGPT Authors
      url: https://github.com/k8sgpt-ai/community
    name: k8sgpt-operator
    type: application
    urls:
    - https://charts.k8sgpt.ai/k8sgpt-operator-0.0.20.tgz
    version: 0.0.20
  - annotations:
      artifacthub.io/categories: monitoring-logging
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: support
          url: https://github.com/k8sgpt-ai/k8sgpt-operator/issues/new
        - name: community
          url: https://github.com/k8sgpt-ai/community
    apiVersion: v2
    appVersion: 0.0.19
    created: "2023-06-20T09:01:06.717591751Z"
    description: Automatic SRE Superpowers within your Kubernetes cluster
    digest: 433428a5ffaf61355a8fa095fd1addafe73ba7b725746887123abba1bc61c92f
    maintainers:
    - email: noreply@k8sgpt.ai
      name: The K8sGPT Authors
      url: https://github.com/k8sgpt-ai/community
    name: k8sgpt-operator
    type: application
    urls:
    - https://charts.k8sgpt.ai/k8sgpt-operator-0.0.19.tgz
    version: 0.0.19
  - annotations:
      artifacthub.io/categories: monitoring-logging
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: support
          url: https://github.com/k8sgpt-ai/k8sgpt-operator/issues/new
        - name: community
          url: https://github.com/k8sgpt-ai/community
    apiVersion: v2
    appVersion: 0.0.17
    created: "2023-06-05T19:02:50.986964646Z"
    description: Automatic SRE Superpowers within your Kubernetes cluster
    digest: 74e6a8b74fd1972871159c5c0d84c1c67934c765e47419b0da3b919f1202302b
    maintainers:
    - email: noreply@k8sgpt.ai
      name: The K8sGPT Authors
      url: https://github.com/k8sgpt-ai/community
    name: k8sgpt-operator
    type: application
    urls:
    - https://charts.k8sgpt.ai/k8sgpt-operator-0.0.17.tgz
    version: 0.0.17
  - annotations:
      artifacthub.io/categories: monitoring-logging
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: support
          url: https://github.com/k8sgpt-ai/k8sgpt-operator/issues/new
        - name: community
          url: https://github.com/k8sgpt-ai/community
    apiVersion: v2
    appVersion: 0.0.16
    created: "2023-05-24T11:59:30.521452702Z"
    description: Automatic SRE Superpowers within your Kubernetes cluster
    digest: 2871202542a379fee6864f042e9b395d01e6b504d91edb98840c420ed0804e00
    maintainers:
    - email: noreply@k8sgpt.ai
      name: The K8sGPT Authors
      url: https://github.com/k8sgpt-ai/community
    name: k8sgpt-operator
    type: application
    urls:
    - https://charts.k8sgpt.ai/k8sgpt-operator-0.0.16.tgz
    version: 0.0.16
  - annotations:
      artifacthub.io/categories: monitoring-logging
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: support
          url: https://github.com/k8sgpt-ai/k8sgpt-operator/issues/new
        - name: community
          url: https://github.com/k8sgpt-ai/community
    apiVersion: v2
    appVersion: 0.0.15
    created: "2023-05-22T06:38:01.846093692Z"
    description: Automatic SRE Superpowers within your Kubernetes cluster
    digest: 3db9d71fff5b341d4e5aa7b21111254c9009be0bd57711bb83b182419ba94b9a
    maintainers:
    - email: noreply@k8sgpt.ai
      name: The K8sGPT Authors
      url: https://github.com/k8sgpt-ai/community
    name: k8sgpt-operator
    type: application
    urls:
    - https://charts.k8sgpt.ai/k8sgpt-operator-0.0.15.tgz
    version: 0.0.15
  - annotations:
      artifacthub.io/categories: monitoring-logging
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: support
          url: https://github.com/k8sgpt-ai/k8sgpt-operator/issues/new
        - name: community
          url: https://github.com/k8sgpt-ai/community
    apiVersion: v2
    appVersion: 0.0.14
    created: "2023-05-12T11:27:21.997534822Z"
    description: Automatic SRE Superpowers within your Kubernetes cluster
    digest: eea442765ad5095f64d633e761c2b6fc99004615444bf12b618808666cfdd479
    maintainers:
    - email: noreply@k8sgpt.ai
      name: The K8sGPT Authors
      url: https://github.com/k8sgpt-ai/community
    name: k8sgpt-operator
    type: application
    urls:
    - https://charts.k8sgpt.ai/k8sgpt-operator-0.0.14.tgz
    version: 0.0.14
  - annotations:
      artifacthub.io/categories: monitoring-logging
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: support
          url: https://github.com/k8sgpt-ai/k8sgpt-operator/issues/new
        - name: community
          url: https://github.com/k8sgpt-ai/community
    apiVersion: v2
    appVersion: 0.0.13
    created: "2023-05-11T12:58:23.545975048Z"
    description: Automatic SRE Superpowers within your Kubernetes cluster
    digest: 482232501045c41f1a5f725990355f2cb70bd7d935deb54108af68d2ffa8ae9e
    maintainers:
    - email: noreply@k8sgpt.ai
      name: The K8sGPT Authors
      url: https://github.com/k8sgpt-ai/community
    name: k8sgpt-operator
    type: application
    urls:
    - https://charts.k8sgpt.ai/k8sgpt-operator-0.0.13.tgz
    version: 0.0.13
  - annotations:
      artifacthub.io/categories: monitoring-logging
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: support
          url: https://github.com/k8sgpt-ai/k8sgpt-operator/issues/new
        - name: community
          url: https://github.com/k8sgpt-ai/community
    apiVersion: v2
    appVersion: 0.0.12
    created: "2023-05-10T11:50:32.980526557Z"
    description: Automatic SRE Superpowers within your Kubernetes cluster
    digest: 015d9a9dad9458897260f8e3d4617fe7b69d3b30e799fb1995eaa39083947451
    maintainers:
    - email: noreply@k8sgpt.ai
      name: The K8sGPT Authors
      url: https://github.com/k8sgpt-ai/community
    name: k8sgpt-operator
    type: application
    urls:
    - https://charts.k8sgpt.ai/k8sgpt-operator-0.0.12.tgz
    version: 0.0.12
  - annotations:
      artifacthub.io/categories: monitoring-logging
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: support
          url: https://github.com/k8sgpt-ai/k8sgpt-operator/issues/new
        - name: community
          url: https://github.com/k8sgpt-ai/community
    apiVersion: v2
    appVersion: 0.0.11
    created: "2023-05-09T09:21:12.534917585Z"
    description: Automatic SRE Superpowers within your Kubernetes cluster
    digest: 7844953a50cbfda1c531fdbff09f465bb7ef5b46526e8e6fcc5ad10ced29d73e
    maintainers:
    - email: noreply@k8sgpt.ai
      name: The K8sGPT Authors
      url: https://github.com/k8sgpt-ai/community
    name: k8sgpt-operator
    type: application
    urls:
    - https://charts.k8sgpt.ai/k8sgpt-operator-0.0.11.tgz
    version: 0.0.11
  - annotations:
      artifacthub.io/categories: monitoring-logging
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: support
          url: https://github.com/k8sgpt-ai/k8sgpt-operator/issues/new
        - name: community
          url: https://github.com/k8sgpt-ai/community
    apiVersion: v2
    appVersion: 0.0.10
    created: "2023-05-09T08:14:37.426268197Z"
    description: Automatic SRE Superpowers within your Kubernetes cluster
    digest: 8c2a798e120169df06d62afc8646aa8e44a770109a491ef8560682a2b5a4d537
    maintainers:
    - email: noreply@k8sgpt.ai
      name: The K8sGPT Authors
      url: https://github.com/k8sgpt-ai/community
    name: k8sgpt-operator
    type: application
    urls:
    - https://charts.k8sgpt.ai/k8sgpt-operator-0.0.10.tgz
    version: 0.0.10
  - annotations:
      artifacthub.io/categories: monitoring-logging
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: support
          url: https://github.com/k8sgpt-ai/k8sgpt-operator/issues/new
        - name: community
          url: https://github.com/k8sgpt-ai/community
    apiVersion: v2
    appVersion: 0.0.9
    created: "2023-04-28T20:34:31.585190404Z"
    description: Automatic SRE Superpowers within your Kubernetes cluster
    digest: a09fe2a7ed192e912f7c700946bb6617bc89a3a0d1fd11bd759dc416e19b154d
    maintainers:
    - email: noreply@k8sgpt.ai
      name: The K8sGPT Authors
      url: https://github.com/k8sgpt-ai/community
    name: k8sgpt-operator
    type: application
    urls:
    - https://charts.k8sgpt.ai/k8sgpt-operator-0.0.9.tgz
    version: 0.0.9
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2023-04-28T13:45:11.377669491Z"
    description: A Helm chart for Kubernetes
    digest: 4791df675670307b34145dd34a9ae4044d321001385e2da8b6ffc46ea49d3e79
    maintainers:
    - email: noreply@k8sgpt.ai
      name: The K8sGPT Authors
      url: https://github.com/k8sgpt-ai/community
    name: k8sgpt-operator
    type: application
    urls:
    - https://charts.k8sgpt.ai/k8sgpt-operator-0.0.8.tgz
    version: 0.0.8
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2023-04-28T13:20:41.016484455Z"
    description: A Helm chart for Kubernetes
    digest: 2a3f987feeaa2acfe9377739f10c860916e69b80701482318ecf97589283eb2d
    maintainers:
    - email: noreply@k8sgpt.ai
      name: The K8sGPT Authors
      url: https://github.com/k8sgpt-ai/community
    name: k8sgpt-operator
    type: application
    urls:
    - https://charts.k8sgpt.ai/charts/charts/k8sgpt-operator-0.0.6.tgz
    version: 0.0.6
generated: "2024-02-02T08:13:57.323745518Z"
